export const GET_ACTIVITIES_START = 'GET_ACTIVITIES_START';
export const GET_ACTIVITIES_SUCCESS = 'GET_ACTIVITIES_SUCCESS';
export const GET_ACTIVITIES_FAIL = 'GET_ACTIVITIES_FAIL';

export const GET_EXECUTIVE_SUMMARY_START = 'GET_EXECUTIVE_SUMMARY_START';
export const GET_EXECUTIVE_SUMMARY_SUCCESS = 'GET_EXECUTIVE_SUMMARY_SUCCESS';
export const GET_EXECUTIVE_SUMMARY_FAIL = 'GET_EXECUTIVE_SUMMARY_FAIL';
