export const GET_EXECUTIVE_SUMMARY_START = 'GET_EXECUTIVE_SUMMARY_START';
export const GET_EXECUTIVE_SUMMARY_SUCCESS = 'GET_EXECUTIVE_SUMMARY_SUCCESS';
export const GET_EXECUTIVE_SUMMARY_FAIL = 'GET_EXECUTIVE_SUMMARY_FAIL';

